### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by breakingflower** [sonocotta/esp32-audio-development-kit#2]
Hi

I was looking to build several wifi speakers with DAC for my home multiroom audio solution, I would like to contribute or pre-order if that would already be possible. I saw that the latest activity was 4m ago, are you still working on this project? Looks super cool.

**Comment by anabolyc** [comment]
Hi @fl0r1s . I'm working on the Crowd Supply campaign at the moment, and hope that boards will be available for buying soon. At this moment I can offer you pre-production samples for beta-testing. Please reach me out at andriy@sonocotta.com, I'd really like to hear what are you building and how can I support you in it.

**Comment by anabolyc** [comment]
Hi @fl0r1s . [Campaign](https://www.crowdsupply.com/sonocotta/loud-esp) is live now.
