### ISSUE TITLE
Actual hardware source CAD is missing

### ISSUE THREAD

**Issue by Goury** [sonocotta/esp32-audio-development-kit#3]
Where is it?
Can't find it, PDF is not source code, it's mostly useless.

**Comment by anabolyc** [comment]
Hi @Goury it is created in web IDE, so not much more I can share in terms of schematics. As for PCB, I can (and will) upload PDFs for PCB as well. 

Can you please share what are you looking for exactly?

**Comment by Goury** [comment]
@anabolyc it was created in EasyEDA, so you can totally share it either by a link or by exporting a file (yup, it does let you save a file locally).
Please do that, a PDF is useless.

Right-click the project in the Project tab, manage→share, fill the form, get the link
Here's an example: https://oshwlab.com/goury/light

**Comment by anabolyc** [comment]
> it does let you save a file locally

Good to know. But since I'm in the middle of crowd supply campaign preparation, I'm sure you'll understand, not looking to provide an easy way to clone the board.

> PDF is useless

again useless for what exactly? what are you trying to do?

**Comment by Goury** [comment]
> what are you trying to do?

@anabolyc clone the board of course.
But I can also improve something or integrate it in something bigger.
Or integrate something else into it.

You can't claim it's under GNU GPL or call it "free hardware" if you don't share the actual source.
At least sell the source files for a price.
Or put a promise to release em at a certain date and actually do so.

**Comment by Goury** [comment]
Also github's GUI is &#%!

**Comment by anabolyc** [comment]
I'm plan to release full source after campaign finishes. For now cannot give you exact date though.

**Comment by anabolyc** [comment]
I'm plan to release full source after campaign finishes. For now cannot give you exact date though.

> You can't claim it's under GNU GPL or call it "free hardware" if you don't share the actual source.

I'm pretty sure I can. You have schematics, you're free to use it in your work. Open hardware doesn't imply easy cloning, I'm afraid

**Comment by Goury** [comment]
> plan to release

Noice, ping this thread when it happens please.

> Open hardware doesn't imply easy cloning

It does, but I don't feel like challenging this in a court of law.
One of the ideas is that no one is in control of the hardware.
If a user can't easily clone of modify it, it's not open.

**Comment by 01GOD** [comment]
Sigh...such a letdown. Totally thought the EDA files were in the repo because it said "open source".

I'd truly appreciate the EDA project files. I have one of those touchscreens here now. I'm planning to modify it, but I'd appreciate it as a good PCB design reference as I am still learning PCB design. 

Thanks in advance for posting those EDA  (board and schematic) files this week. 

Edit: Saw now it is literally advertised as "open source hardware". That is really sleazy if the EDA files weren't posted. Is this a pcbway company github repo? Because that kinda behavior seems sadly the sort of sleazy thing that company would maybe do. (it's in china)

**Comment by 01GOD** [comment]
The crowdfunding page said that was fully funded in April and it's already September now.

**Comment by anabolyc** [comment]
Hey @Goury @01GOD just [added](https://github.com/sonocotta/esp32-audio-development-kit/commit/d3850d11cdd37943bcafe332e667b731caa46f93) EasyEDA exported jsons. You may have a look.

**Comment by 01GOD** [comment]
@anabolyc : Thanks for posting those. Sadly the schematic and PCB seem to be unlinked when opened that way though. Posting that on oshwlab.com (it's a JLC thing) would make it easy to open directly in the editor and the schematic and PCB should stay linked that way. Alternatively, can export Altium project from EasyEDA. On the right track though, so thanks in advance for posting that!

**Comment by 01GOD** [comment]
@anabolyc : PS: Recommend the best online repository of PCB modules? (common modules, such as DAC reference board designs and so on) Thankfully at the point where ready to build board designs from such modules.
